name: matrix-algebra
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip
  - pip:
    - pandas==1.5.0
    - scikit-learn==1.1.2
    - numpy==1.23.3
    - uproot==4.2.3
    - awkward==1.10.1
    - matplotlib==3.6.1
    - seaborn==0.12.0
    - statsmodels==0.13.2
    - tqdm==4.64.1
    - scipy==1.9.2
    - shap==0.41.0
    - pickleshare==0.7.5
    - plotly==5.10.0
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyter-server
    - jupyterlab-pygments
    - jupyterlab-widgets
    - notebook
    - matplotlib-inline==0.1.6
    - iminuit==2.17.0
    - pytest==7.1.3
    - oct2py==5.2.0
    - octave-kernel==0.32.0
    - sympy==1.11.1